apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-service-chart
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ./helm_charts/api-service
    repoURL: 'https://github.com/Ahmed-Soli/helm_chart_flask-api-app.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
