---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: ahmedsoliman202/falsk-app-api-service
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: api-service-svc
spec:
  selector:
    app: api-service
  ports:
    - protocol: "TCP"
      port: 5000 # The port that the service is running on in the cluster
      targetPort: 5000 # The port exposed by the service/ the poer the app is running on
      nodePort: 30008 # The port I can access the app on using my PC
  type: NodePort  # type of the service.
---